### PR TITLE
Add immer 100 times to make it faster

### PR DESCRIPTION
**Pull request by chrisparton1991**

### CODE REVIEW

**Comment by pbrdmn** [comment]
C'mon, at least make those image buffers immutable.

**Comment by pbrdmn** [comment]
Is this how it works? -> https://github.com/jkells/siligong-lucky-door/pull/2/commits/ec83f894522c71e7ea44542ab47452e47f7d9b65

**Comment by ramblingenzyme** [comment]
Oh dear. @jkells when are you going to merge these great changes???
Can't believe the maintainer could be such a jerk! inb4 conversation limited to contributors. 😠

**Comment by jkells** [comment]
Looks good to me!

**Pull request closed without merging**
